<?php
use Phalcon\Tag as Tag;
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <?php
    echo Tag::getTitle();
    echo Tag::stylesheetLink('bootstrap/css/bootstrap.css');
    echo Tag::stylesheetLink('bootstrap/css/bootstrap-responsive.css');
    ?>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="#">Phalcon - sandbox</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li><?php echo $this->tag->linkTo("index/index", "Home") ?></li>
                <li><?php echo $this->tag->linkTo("session/index", "Logowanie") ?></li>
                <li><?php echo $this->tag->linkTo("signup/index", "Rejestracja") ?></li>
                <li><?php echo $this->tag->linkTo("index/restricted", "Strefa zalogowanych") ?></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <?php if(!$this->session->get('auth')):?>
                    <li><a>Witaj Nieznajomy</a></li>
                <?php else: ?>
                    <li><a class="glyphicon glyphicon-user"> Witaj <?php echo $this->session->get('auth')['name'];?></a></li>
                <?php endif; ?>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>
<div class="container" style="margin-top: 80px; margin-bottom: 80px;">
    <?php echo $this->getContent(); ?>
</div>
<div class="footer-bottom">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
                © 2015, Moose INC., All rights reserved
            </div>
            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
                <a href="#">Moose Inc. </a> | Projekt demonstracyjny
            </div>
        </div>
    </div>
</div>
<?php
echo Tag::javascriptInclude('js/jquery.min.js');
echo Tag::javascriptInclude('bootstrap/js/bootstrap.js');
?>
</body>
</html>